# Generated by Django 6.0.5 on 2026-06-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
